<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="FB_FuseTest" Id="{e47d6a39-c379-42ae-ae60-e27562337e6d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FuseTest
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_FuseTest">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>