<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="FB_SimpleFuse" Id="{6ba8ae37-75f1-446b-9d7f-12fc08dcb036}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SimpleFuse
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	Chn1 : EL922x_ChannelBasic;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SimpleFuse">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>