<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_Axis" Id="{c140482e-603b-4d92-ba54-92c858058e3b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Axis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbIdleState : FB_Idle(THIS);
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Axis">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>