<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{f20f72a3-44bd-4b01-bab9-6aeb1376a30d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	chn1 : FuseChannelBasic;
	chn2 : FuseChannelExtended;
	FuseModule : FuseModuleEL922x(chn1,chn2);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="30" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>