<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="FB_AnalogueInputBase" Id="{ffe48a9a-1d37-40f8-b7a7-45cd91910e96}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AnalogueInputBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	processData : AnalogueStatus;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AnalogueInputBase">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>